apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: team-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: backend-html

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: team-web
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
