apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: team-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "while true; do echo hello from app-a; sleep 10; done"]
