apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-html
  namespace: team-web
data:
  index.html: |
    <html><body><h1>Backend Page</h1></body></html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: team-web
data:
  index.html: |
    <html><body><h1>Frontend Page</h1></body></html>
