apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-sa
  namespace: team-red
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-sa-role
  namespace: team-red
rules:
- apiGroups: [""]
  resources: ["secrets","pods","deployments","configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-sa-role
  namespace: team-red
subjects:
- kind: ServiceAccount
  name: pod-sa
  namespace: team-red
roleRef:
  kind: Role
  name: pod-sa-role
  apiGroup: rbac.authorization.k8s.io
