apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: team-red
spec:
  containers:
  - name: c1
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/secret-volume"
  volumes:
  - name: secret-vol
    secret:
      secretName: secret1