apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: team-red
spec:
  containers:
  - name: c2
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret2
          key: PASSWORD